version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directories:
  - "/"
  - "/.github/actions/*/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 0

# Maintain dependencies for npm
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 0
  labels: ["component/dependencies"]
  ignore:
  - # Needs to be updated along with NodeJS version.
    dependency-name: "@types/node"
    update-types: [version-update:semver-major]
  - # We don't utilize @rancher/shell in a meaningful way. It is safe to
    # ignore until we arrive a solution that uses it.
    dependency-name: "@rancher/shell"
    versions: [">0.1"]
  - # We are currently using @vue/cli-service which depends on an older version
    # of webpack.  Upgrading webpack past what we currently have causes
    # conflicts between the different versions of webpack.  Disable further
    # updates of webpack until we can migrate off @vue/cli-service (which is
    # unlikely to be fixed as it is in maintenance mode).
    dependency-name: "webpack"

# Maintain dependencies for Golang
- package-ecosystem: "gomod"
  directories:
  - "/src/go/*"
  - "/src/go/**/*"
  - "/scripts"
  schedule:
    interval: "daily"
  cooldown:
   default-days: 7
  open-pull-requests-limit: 0
  labels: ["component/dependencies"]
  ignore:
  - # Swagger dependencies must match whatever the CLI generate.
    dependency-name: "github.com/go-openapi/swag"
  groups:
    golang-x:
      patterns: ["golang.org/x/*"]
    k8s:
      patterns: ["k8s.io/*"]

- package-ecosystem: gomod
  directory: /rdd
  schedule:
    interval: daily
  cooldown:
    default-days: 7
  ignore:
  - { dependency-name: k8s.io/api }
  - { dependency-name: k8s.io/apiextensions-apiserver }
  - { dependency-name: k8s.io/apimachinery }
  - { dependency-name: k8s.io/apiserver }
  - { dependency-name: k8s.io/cli-runtime }
  - { dependency-name: k8s.io/client-go }
  - { dependency-name: k8s.io/cloud-provider }
  - { dependency-name: k8s.io/cluster-bootstrap }
  - { dependency-name: k8s.io/code-generator }
  - { dependency-name: k8s.io/component-base }
  - { dependency-name: k8s.io/component-helpers }
  - { dependency-name: k8s.io/controller-manager }
  - { dependency-name: k8s.io/cri-api }
  - { dependency-name: k8s.io/cri-client }
  - { dependency-name: k8s.io/csi-translation-lib }
  - { dependency-name: k8s.io/dynamic-resource-allocation }
  - { dependency-name: k8s.io/endpointslice }
  - { dependency-name: k8s.io/externaljwt }
  - { dependency-name: k8s.io/kms }
  - { dependency-name: k8s.io/kube-aggregator }
  - { dependency-name: k8s.io/kube-controller-manager }
  - { dependency-name: k8s.io/kube-proxy }
  - { dependency-name: k8s.io/kube-scheduler }
  - { dependency-name: k8s.io/kubectl }
  - { dependency-name: k8s.io/kubelet }
  - { dependency-name: k8s.io/metrics }
  - { dependency-name: k8s.io/mount-utils }
  - { dependency-name: k8s.io/pod-security-admission }
  - { dependency-name: k8s.io/sample-apiserver }
  - { dependency-name: k8s.io/sample-cli-plugin }
  - { dependency-name: k8s.io/sample-controller }
  groups:
    golang-x:
      patterns: [ golang.org/x/* ]
