// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	containersv1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/containers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ContainerStatusApplyConfiguration represents a declarative configuration of the ContainerStatus type for use
// with apply.
//
// ContainerStatus defines the observed state of the container.
type ContainerStatusApplyConfiguration struct {
	// Name of the container; this is distinct from the container ID.
	Name *string `json:"name,omitempty"`
	// Namespace is the container namespace; refers to a `ContainerNamespace`
	// object in the same Kubernetes namespace.
	Namespace *string `json:"namespace,omitempty"`
	// Path to the executable (within the image) for the process.
	Path *string `json:"path,omitempty"`
	// Args is the arguments to the executable.
	Args []string `json:"args,omitempty"`
	// Image is the image the container was created with.
	Image *string `json:"image,omitempty"`
	// Ports describes the exposed ports of the container.
	Ports []ContainerPortApplyConfiguration `json:"ports,omitempty"`
	// Labels are the container labels.
	Labels map[string]string `json:"labels,omitempty"`
	// Status of the container.
	Status *containersv1alpha1.ContainerStatusValue `json:"status,omitempty"`
	// Pid is the process identifier for the main process in the container.
	Pid *int32 `json:"pid,omitempty"`
	// ExitCode is the exit status of the main process in the container.
	ExitCode *int32 `json:"exitCode,omitempty"`
	// Error message if the container has failed to start.
	Error *string `json:"error,omitempty"`
	// CreatedAt is the time this container was initially created.
	CreatedAt *v1.Time `json:"createdAt,omitempty"`
	// StartedAt is the time this container was started; unset if the container is stopped.
	StartedAt *v1.Time `json:"startedAt,omitempty"`
	// FinishedAt is the time this container was last stopped; unset if the container never ran.
	FinishedAt *v1.Time `json:"finishedAt,omitempty"`
	// Conditions represent the calculated state of the container.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Known condition types include:
	// - "Running": the container is running; this may also be paused.
	// - "Paused": the container is paused.
	// - "Restarting": the container is restarting.
	// - "OOMKilled": a process within this container has been killed because it ran out of memory
	// since the container was last started.
	// - "Dead": the container is dead.
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// LastAction records the most recent action requested via the
	// AnnotationAction annotation and its outcome. Persists after the
	// action completes until overwritten by the next action.
	LastAction *ContainerLastActionApplyConfiguration `json:"lastAction,omitempty"`
}

// ContainerStatusApplyConfiguration constructs a declarative configuration of the ContainerStatus type for use with
// apply.
func ContainerStatus() *ContainerStatusApplyConfiguration {
	return &ContainerStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithName(value string) *ContainerStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithNamespace(value string) *ContainerStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithPath(value string) *ContainerStatusApplyConfiguration {
	b.Path = &value
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *ContainerStatusApplyConfiguration) WithArgs(values ...string) *ContainerStatusApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithImage(value string) *ContainerStatusApplyConfiguration {
	b.Image = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *ContainerStatusApplyConfiguration) WithPorts(values ...*ContainerPortApplyConfiguration) *ContainerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPorts")
		}
		b.Ports = append(b.Ports, *values[i])
	}
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ContainerStatusApplyConfiguration) WithLabels(entries map[string]string) *ContainerStatusApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithStatus(value containersv1alpha1.ContainerStatusValue) *ContainerStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithPid sets the Pid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pid field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithPid(value int32) *ContainerStatusApplyConfiguration {
	b.Pid = &value
	return b
}

// WithExitCode sets the ExitCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExitCode field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithExitCode(value int32) *ContainerStatusApplyConfiguration {
	b.ExitCode = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithError(value string) *ContainerStatusApplyConfiguration {
	b.Error = &value
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithCreatedAt(value v1.Time) *ContainerStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithStartedAt(value v1.Time) *ContainerStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithFinishedAt sets the FinishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FinishedAt field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithFinishedAt(value v1.Time) *ContainerStatusApplyConfiguration {
	b.FinishedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ContainerStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ContainerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLastAction sets the LastAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastAction field is set to the value of the last call.
func (b *ContainerStatusApplyConfiguration) WithLastAction(value *ContainerLastActionApplyConfiguration) *ContainerStatusApplyConfiguration {
	b.LastAction = value
	return b
}
