// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	containersv1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/containers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ContainerLastActionApplyConfiguration represents a declarative configuration of the ContainerLastAction type for use
// with apply.
//
// ContainerLastAction records the most recent action requested via the
// AnnotationAction annotation and its outcome.
type ContainerLastActionApplyConfiguration struct {
	// Action is the action that was requested.
	Action *containersv1alpha1.ContainerAction `json:"action,omitempty"`
	// State is the outcome of the action.
	State *containersv1alpha1.ContainerActionState `json:"state,omitempty"`
	// Error is the error message if the action failed.
	Error *string `json:"error,omitempty"`
	// ObservedAt is when the reconciler began processing the action annotation.
	// Backlog may delay this relative to the user's write time, and dispatch
	// (especially restart's grace period) extends the gap to CompletedAt.
	ObservedAt *v1.Time `json:"observedAt,omitempty"`
	// CompletedAt is when the action completed, regardless of outcome.
	CompletedAt *v1.Time `json:"completedAt,omitempty"`
}

// ContainerLastActionApplyConfiguration constructs a declarative configuration of the ContainerLastAction type for use with
// apply.
func ContainerLastAction() *ContainerLastActionApplyConfiguration {
	return &ContainerLastActionApplyConfiguration{}
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *ContainerLastActionApplyConfiguration) WithAction(value containersv1alpha1.ContainerAction) *ContainerLastActionApplyConfiguration {
	b.Action = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ContainerLastActionApplyConfiguration) WithState(value containersv1alpha1.ContainerActionState) *ContainerLastActionApplyConfiguration {
	b.State = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *ContainerLastActionApplyConfiguration) WithError(value string) *ContainerLastActionApplyConfiguration {
	b.Error = &value
	return b
}

// WithObservedAt sets the ObservedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedAt field is set to the value of the last call.
func (b *ContainerLastActionApplyConfiguration) WithObservedAt(value v1.Time) *ContainerLastActionApplyConfiguration {
	b.ObservedAt = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *ContainerLastActionApplyConfiguration) WithCompletedAt(value v1.Time) *ContainerLastActionApplyConfiguration {
	b.CompletedAt = &value
	return b
}
