// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/containers/v1alpha1"
	containersv1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/containers/v1alpha1/applyconfiguration/containers/v1alpha1"
	internal "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/containers/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=containers.rancherdesktop.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Container"):
		return &containersv1alpha1.ContainerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerLastAction"):
		return &containersv1alpha1.ContainerLastActionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerNamespace"):
		return &containersv1alpha1.ContainerNamespaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerPort"):
		return &containersv1alpha1.ContainerPortApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerPortBinding"):
		return &containersv1alpha1.ContainerPortBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ContainerStatus"):
		return &containersv1alpha1.ContainerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Image"):
		return &containersv1alpha1.ImageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ImageStatus"):
		return &containersv1alpha1.ImageStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Volume"):
		return &containersv1alpha1.VolumeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VolumeStatus"):
		return &containersv1alpha1.VolumeStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
