name: Get Token
description: >-
  This action attempts to get a token with the requested permissions; if this is
  not running from the upstream repository, it attempts to get the token from a
  secret.  Otherwise, it uses the vault actions.
  This requires permissions set described in
  https://github.com/rancher-eio/read-vault-secrets
inputs:
  token-secret:
    description: Secret to fall back to
    required: false
outputs:
  token:
    description: The GitHub token retrieved
    value: ${{ github.repository_owner == 'rancher-sandbox' && steps.copy-token.outputs.token || steps.get-secret.outputs.token }}
runs:
  using: composite
  steps:
  - id: vault
    name: Read vault secrets
    if: github.repository_owner == 'rancher-sandbox'
    uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89 # main
    with:
      secrets: |
        github/token/${{ github.repository_owner }}--rancher-desktop-daemon--pull_requests--write token | GH_TOKEN
  - id: copy-token
    if: github.repository_owner == 'rancher-sandbox'
    shell: bash
    run: echo "token=$GH_TOKEN" >> "$GITHUB_OUTPUT"
  - id: get-secret
    name: Fetch secret.
    if: github.repository_owner != 'rancher-sandbox'
    run: echo "token=$SECRET" >> "$GITHUB_OUTPUT"
    shell: bash
    env:
      SECRET: ${{ inputs.token-secret }}
