name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-pr-number:
    name: Lookup Pull Request
    outputs:
      number: ${{ steps.lookup.outputs.number }}
    runs-on: ubuntu-latest
    steps:
    - id: lookup
      if: >-
        github.event_name == 'push' &&
        github.repository_owner == 'rancher-sandbox' &&
        github.ref_type == 'branch' &&
        !github.ref_protected
      shell: bash
      run: >-
        printf "number=%s\n" >>"$GITHUB_OUTPUT"
        $(gh pr list
        --repo ${{ github.repository }}
        --search ${{ github.sha }}
        --json number
        --jq '.[0].number // 0')
      env:
        GH_TOKEN: ${{ github.token }}
  lint-rdd:
    name: Lint RDD
    needs: get-pr-number
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - name: "Windows: Set up line endings"
      if: runner.os == 'Windows'
      run: |
        git config --global --replace-all core.autocrlf false # spellchecker:ignore
        git config --global --replace-all core.eol lf # spellchecker:ignore
        git config --global --replace-all core.longpath true #spellchecker:ignore
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
    - run: make lint-rdd
  test:
    name: Unit tests
    needs: get-pr-number
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: go.mod
    - run: make test
  lint-bats:
    name: Lint BATS
    needs: get-pr-number
    runs-on: ubuntu-latest
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        cache: false
        go-version-file: go.mod
    - run: make lint-bats
  spelling:
    name: Check Spelling
    needs: get-pr-number
    runs-on: ubuntu-latest
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - run: sudo apt install cpanminus
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        submodules: recursive
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        cache: false
        go-version-file: go.mod
    - run: make spelling
  ltag:
    name: Check license tags
    needs: get-pr-number
    runs-on: ubuntu-latest
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        cache: false
        go-version-file: go.mod
    - run: make check-ltag
