name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-pr-number:
    name: Lookup Pull Request
    outputs:
      number: ${{ steps.lookup.outputs.number }}
    runs-on: ubuntu-latest
    steps:
    - id: lookup
      if: >-
        github.event_name == 'push' &&
        github.repository_owner == 'rancher-sandbox' &&
        github.ref_type == 'branch' &&
        !github.ref_protected
      shell: bash
      run: >-
        printf "number=%s\n" >>"$GITHUB_OUTPUT"
        $(gh pr list
        --repo ${{ github.repository }}
        --search ${{ github.sha }}
        --json number
        --jq '.[0].number // 0')
      env:
        GH_TOKEN: ${{ github.token }}
  golangci-lint:
    name: golangci-lint
    needs: get-pr-number
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - name: "Windows: Set up line endings"
      if: runner.os == 'Windows'
      run: |
        git config --global --replace-all core.autocrlf false # spellchecker:ignore
        git config --global --replace-all core.eol lf # spellchecker:ignore
        git config --global --replace-all core.longpath true #spellchecker:ignore
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9.0.0
  test:
    name: Unit tests
    needs: get-pr-number
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
    - run: make test
  bats:
    name: Lint BATS
    needs: get-pr-number
    runs-on: ubuntu-latest
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        cache: false
        go-version-file: go.mod
    - run: make -C bats lint
  spelling:
    name: Check Spelling
    needs: get-pr-number
    runs-on: ubuntu-latest
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - run: sudo apt install cpanminus
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
        submodules: recursive
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        cache: false
        go-version-file: go.mod
    - run: make spelling
  ltag:
    name: Check license tags
    needs: get-pr-number
    runs-on: ubuntu-latest
    if: ${{ ! needs.get-pr-number.outputs.number }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        cache: false
        go-version-file: go.mod
    - run: make check-ltag
